// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (c) 2024 Sam Tran

export const mockArticles = [
  {
    'date': '2024-06-02T18:00:00',
    'id': 283423,
    'link': 'https://www.omgubuntu.co.uk/2024/06/convert-text-documents-easily-ubuntu',
    'thumbnail': null,
    'title': 'New App Makes Converting Text Documents on Ubuntu Easier',
    'unread': false,
  },
  {
    'date': '2024-05-30T21:22:00',
    'id': 283383,
    'link': 'https://www.omgubuntu.co.uk/2024/05/wsl-gui-settings-apps-coming-soon',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2024/05/windows-tux-thumbnail-350x200.jpg',
    'title': 'Microsoft Announce WSL Updates, Including New Settings App',
    'unread': false,
  },
  {
    'date': '2024-05-29T22:20:00',
    'id': 283328,
    'link': 'https://www.omgubuntu.co.uk/2024/05/8bitdo-keyboard-m-ibm-model-m-inspired',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2024/05/8bitdo-keyboard-m-350x200.jpg',
    'title': 'IBM&#8217;s Iconic Model-M Keyboard Reimagined by 8BitDo',
    'unread': false,
  },
  {
    'date': '2024-05-28T21:48:00',
    'id': 283303,
    'link': 'https://www.omgubuntu.co.uk/2024/05/firefox-126-bug-fix-drag-and-drop-linux',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2022/06/firefox-logo-on-an-orange-background-350x200.jpg',
    'title': 'Mozilla Firefox 126.0.1 Fixes Drag and Drop Quirk on Linux',
    'unread': false,
  },
  {
    'date': '2024-05-28T19:35:16',
    'id': 283253,
    'link': 'https://www.omgubuntu.co.uk/2024/05/ubuntu-24-04-risc-v-computer-milkv',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2024/05/milkv-mars-ubuntu-24.04-350x200.jpg',
    'title': 'Ubuntu 24.04 Arrives on Mars – the Milk-V Mars (RISC-V Computer)',
    'unread': false,
  },
  {
    'date': '2024-05-27T22:23:00',
    'id': 283168,
    'link': 'https://www.omgubuntu.co.uk/2024/05/day-progress-time-tracking-gnome-extension',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2024/05/day-progress-gnome-shell-extnsion-350x200.jpg',
    'title': 'Track Time Differently with &#8216;Day Progress&#8217; for GNOME Shell',
    'unread': false,
  },
  {
    'date': '2024-05-26T17:21:11',
    'id': 283136,
    'link': 'https://www.omgubuntu.co.uk/2024/05/cascadia-code-font-update-large-type-pieces',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2024/05/cascadia-code-update-350x200.jpg',
    'title': 'Microsoft Gives its Open-Source Developer Font Major Update',
    'unread': false,
  },
  {
    'date': '2024-05-24T14:07:37',
    'id': 283080,
    'link': 'https://www.omgubuntu.co.uk/2024/05/rufus-usb-ubuntu-24-04-persistence',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2016/04/usb-live-boot-350x200.jpg',
    'title': 'Rufus Fixes Creation of Persistent Ubuntu 24.04 USBs',
    'unread': false,
  },
  {
    'date': '2024-05-23T15:02:35',
    'id': 283052,
    'link': 'https://www.omgubuntu.co.uk/2024/05/snap-store-website-new-look',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2023/05/ubuntu-logo-and-the-snapcraft-logo-tiled-350x200.jpg',
    'title': 'Snap Store Website Redesign Goes Live – And It Looks Good',
    'unread': false,
  },
  {
    'date': '2024-05-22T16:51:26',
    'id': 282972,
    'link': 'https://www.omgubuntu.co.uk/2024/05/ubuntu-24-04-upgrades-officially-open',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2024/05/noble-upgrade-tile-350x200.jpg',
    'title': 'Ubuntu 24.04 LTS Upgrades Now Officially Enabled',
    'unread': false,
  },
  {
    'date': '2024-05-22T15:45:05',
    'id': 282962,
    'link': 'https://www.omgubuntu.co.uk/2024/05/mozilla-shares-firefox-roadmap',
    'thumbnail': 'https://www.omgubuntu.co.uk/wp-content/uploads/2019/11/firefox-1-350x200.jpg',
    'title': 'Mozilla Reveals New Features Coming to Firefox',
    'unread': false,
  },
];

export const mockResponse = [{
  'id': 283465,
  'date_gmt': '2024-06-03T22:03:20',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/06\/linux-mint-will-hide-unverified-flatpaks',
  'title': { 'rendered': 'Linux Mint Will Hide Unverified Flatpaks in Software Manager' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/277168',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 277168,
      'date': '2024-02-01T00:33:39',
      'slug': 'linux-mint-22-tile',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/01\/linux-mint-22-codename-revealed\/linux-mint-22-tile',
      'title': { 'rendered': 'linux-mint-22-tile' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': '',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1920,
        'height': 1008,
        'file': '2024\/02\/linux-mint-22-tile.jpg',
        'filesize': 191002,
        'sizes': {
          'medium': {
            'file': 'linux-mint-22-tile-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 7300,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-300x158.jpg',
          },
          'large': {
            'file': 'linux-mint-22-tile-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 31975,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-840x441.jpg',
          },
          'thumbnail': {
            'file': 'linux-mint-22-tile-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 10162,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-350x200.jpg',
          },
          'medium_large': {
            'file': 'linux-mint-22-tile-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 27909,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-768x403.jpg',
          },
          '1536x1536': {
            'file': 'linux-mint-22-tile-1536x806.jpg',
            'width': 1536,
            'height': 806,
            'filesize': 91998,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-1536x806.jpg',
          },
          'square-150': {
            'file': 'linux-mint-22-tile-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 5567,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-150x150.jpg',
          },
          'post-list': {
            'file': 'linux-mint-22-tile-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 12252,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-406x232.jpg',
          },
          'featured-post': {
            'file': 'linux-mint-22-tile-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 34156,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile-840x480.jpg',
          },
          'full': {
            'file': 'linux-mint-22-tile.jpg',
            'width': 1920,
            'height': 1008,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/02\/linux-mint-22-tile.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/277168' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=277168',
        }],
      },
    }],
  },
}, {
  'id': 283423,
  'date_gmt': '2024-06-02T18:00:00',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/06\/convert-text-documents-easily-ubuntu',
  'title': { 'rendered': 'New App Makes Converting Text Documents on Ubuntu Easier' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283436',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 283436,
      'date': '2024-06-03T02:35:44',
      'slug': 'document-conversion',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/06\/convert-text-documents-easily-ubuntu\/document-conversion',
      'title': { 'rendered': 'document-conversion' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': 'converting documents',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1920,
        'height': 1008,
        'file': '2024\/06\/document-conversion.jpg',
        'filesize': 199078,
        'sizes': {
          'medium': {
            'file': 'document-conversion-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 7678,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-300x158.jpg',
          },
          'large': {
            'file': 'document-conversion-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 35709,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-840x441.jpg',
          },
          'thumbnail': {
            'file': 'document-conversion-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 10546,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-350x200.jpg',
          },
          'medium_large': {
            'file': 'document-conversion-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 30749,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-768x403.jpg',
          },
          '1536x1536': {
            'file': 'document-conversion-1536x806.jpg',
            'width': 1536,
            'height': 806,
            'filesize': 108567,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-1536x806.jpg',
          },
          'square-150': {
            'file': 'document-conversion-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 5302,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-150x150.jpg',
          },
          'post-list': {
            'file': 'document-conversion-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 12934,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-406x232.jpg',
          },
          'featured-post': {
            'file': 'document-conversion-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 39008,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion-840x480.jpg',
          },
          'full': {
            'file': 'document-conversion.jpg',
            'width': 1920,
            'height': 1008,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/06\/document-conversion.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283436' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=283436',
        }],
      },
    }],
  },
}, {
  'id': 283383,
  'date_gmt': '2024-05-30T21:22:00',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/wsl-gui-settings-apps-coming-soon',
  'title': { 'rendered': 'Microsoft Announce WSL Updates, Including New Settings App' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283407',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 283407,
      'date': '2024-05-31T00:47:57',
      'slug': 'windows-tux-thumbnail',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/wsl-gui-settings-apps-coming-soon\/windows-tux-thumbnail',
      'title': { 'rendered': 'windows-tux-thumbnail' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': '',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1440,
        'height': 825,
        'file': '2024\/05\/windows-tux-thumbnail.jpg',
        'filesize': 65806,
        'sizes': {
          'medium': {
            'file': 'windows-tux-thumbnail-300x172.jpg',
            'width': 300,
            'height': 172,
            'filesize': 5438,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail-300x172.jpg',
          },
          'large': {
            'file': 'windows-tux-thumbnail-840x481.jpg',
            'width': 840,
            'height': 481,
            'filesize': 25314,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail-840x481.jpg',
          },
          'thumbnail': {
            'file': 'windows-tux-thumbnail-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 6660,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail-350x200.jpg',
          },
          'medium_large': {
            'file': 'windows-tux-thumbnail-768x440.jpg',
            'width': 768,
            'height': 440,
            'filesize': 21314,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail-768x440.jpg',
          },
          'square-150': {
            'file': 'windows-tux-thumbnail-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 2924,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail-150x150.jpg',
          },
          'post-list': {
            'file': 'windows-tux-thumbnail-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 8126,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail-406x232.jpg',
          },
          'featured-post': {
            'file': 'windows-tux-thumbnail-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 25207,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail-840x480.jpg',
          },
          'full': {
            'file': 'windows-tux-thumbnail.jpg',
            'width': 1440,
            'height': 825,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/windows-tux-thumbnail.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283407' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=283407',
        }],
      },
    }],
  },
}, {
  'id': 283328,
  'date_gmt': '2024-05-29T22:20:00',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/8bitdo-keyboard-m-ibm-model-m-inspired',
  'title': { 'rendered': 'IBM&#8217;s Iconic Model-M Keyboard Reimagined by 8BitDo' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283332',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 283332,
      'date': '2024-05-30T01:39:09',
      'slug': '8bitdo-keyboard-m',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/8bitdo-keyboard-m-ibm-model-m-inspired\/8bitdo-keyboard-m',
      'title': { 'rendered': '8bitdo-keyboard-m' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': '',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1920,
        'height': 1008,
        'file': '2024\/05\/8bitdo-keyboard-m.jpg',
        'filesize': 268494,
        'sizes': {
          'medium': {
            'file': '8bitdo-keyboard-m-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 10532,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-300x158.jpg',
          },
          'large': {
            'file': '8bitdo-keyboard-m-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 54666,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-840x441.jpg',
          },
          'thumbnail': {
            'file': '8bitdo-keyboard-m-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 14447,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-350x200.jpg',
          },
          'medium_large': {
            'file': '8bitdo-keyboard-m-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 47093,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-768x403.jpg',
          },
          '1536x1536': {
            'file': '8bitdo-keyboard-m-1536x806.jpg',
            'width': 1536,
            'height': 806,
            'filesize': 159604,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-1536x806.jpg',
          },
          'square-150': {
            'file': '8bitdo-keyboard-m-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 5659,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-150x150.jpg',
          },
          'post-list': {
            'file': '8bitdo-keyboard-m-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 18078,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-406x232.jpg',
          },
          'featured-post': {
            'file': '8bitdo-keyboard-m-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 58398,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m-840x480.jpg',
          },
          'full': {
            'file': '8bitdo-keyboard-m.jpg',
            'width': 1920,
            'height': 1008,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/8bitdo-keyboard-m.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283332' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=283332',
        }],
      },
    }],
  },
}, {
  'id': 283303,
  'date_gmt': '2024-05-28T21:48:00',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/firefox-126-bug-fix-drag-and-drop-linux',
  'title': { 'rendered': 'Mozilla Firefox 126.0.1 Fixes Drag and Drop Quirk on Linux' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/252695',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 252695,
      'date': '2022-06-27T13:21:29',
      'slug': 'firefox-logo-on-an-orange-background',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2022\/06\/mozilla-firefox-102-intros-geoclue-support-on-linux-desktop-improves-pdf-viewer\/firefox-logo-on-an-orange-background',
      'title': { 'rendered': 'firefox-logo-on-an-orange-background' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': 'firefox logo on an orange background',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1280,
        'height': 672,
        'file': '2022\/06\/firefox-logo-on-an-orange-background.jpg',
        'filesize': 26328,
        'sizes': {
          'medium': {
            'file': 'firefox-logo-on-an-orange-background-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 4428,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background-300x158.jpg',
          },
          'large': {
            'file': 'firefox-logo-on-an-orange-background-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 17688,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background-840x441.jpg',
          },
          'thumbnail': {
            'file': 'firefox-logo-on-an-orange-background-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 5707,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background-350x200.jpg',
          },
          'medium_large': {
            'file': 'firefox-logo-on-an-orange-background-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 15608,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background-768x403.jpg',
          },
          'square-150': {
            'file': 'firefox-logo-on-an-orange-background-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 3412,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background-150x150.jpg',
          },
          'post-list': {
            'file': 'firefox-logo-on-an-orange-background-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 7042,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background-406x232.jpg',
          },
          'featured-post': {
            'file': 'firefox-logo-on-an-orange-background-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 18800,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background-840x480.jpg',
          },
          'full': {
            'file': 'firefox-logo-on-an-orange-background.jpg',
            'width': 1280,
            'height': 672,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2022\/06\/firefox-logo-on-an-orange-background.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/252695' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=252695',
        }],
      },
    }],
  },
}, {
  'id': 283253,
  'date_gmt': '2024-05-28T19:35:16',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/ubuntu-24-04-risc-v-computer-milkv',
  'title': { 'rendered': 'Ubuntu 24.04 Arrives on Mars \u2013 the Milk-V Mars (RISC-V Computer)' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283259',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 283259,
      'date': '2024-05-28T20:24:54',
      'slug': 'milkv-mars-ubuntu-24-04',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/ubuntu-24-04-risc-v-computer-milkv\/milkv-mars-ubuntu-24-04',
      'title': { 'rendered': 'milkv-mars-ubuntu-24.04' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': '',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1920,
        'height': 1008,
        'file': '2024\/05\/milkv-mars-ubuntu-24.04.jpg',
        'filesize': 238456,
        'sizes': {
          'medium': {
            'file': 'milkv-mars-ubuntu-24.04-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 7830,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-300x158.jpg',
          },
          'large': {
            'file': 'milkv-mars-ubuntu-24.04-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 43047,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-840x441.jpg',
          },
          'thumbnail': {
            'file': 'milkv-mars-ubuntu-24.04-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 10655,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-350x200.jpg',
          },
          'medium_large': {
            'file': 'milkv-mars-ubuntu-24.04-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 36582,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-768x403.jpg',
          },
          '1536x1536': {
            'file': 'milkv-mars-ubuntu-24.04-1536x806.jpg',
            'width': 1536,
            'height': 806,
            'filesize': 134646,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-1536x806.jpg',
          },
          'square-150': {
            'file': 'milkv-mars-ubuntu-24.04-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 6488,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-150x150.jpg',
          },
          'post-list': {
            'file': 'milkv-mars-ubuntu-24.04-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 13529,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-406x232.jpg',
          },
          'featured-post': {
            'file': 'milkv-mars-ubuntu-24.04-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 47223,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04-840x480.jpg',
          },
          'full': {
            'file': 'milkv-mars-ubuntu-24.04.jpg',
            'width': 1920,
            'height': 1008,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/milkv-mars-ubuntu-24.04.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283259' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=283259',
        }],
      },
    }],
  },
}, {
  'id': 283168,
  'date_gmt': '2024-05-27T22:23:00',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/day-progress-time-tracking-gnome-extension',
  'title': { 'rendered': 'Track Time Differently with &#8216;Day Progress&#8217; for GNOME Shell' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283249',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 283249,
      'date': '2024-05-28T17:10:07',
      'slug': 'day-progress-gnome-shell-extnsion',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/day-progress-time-tracking-gnome-extension\/day-progress-gnome-shell-extnsion',
      'title': { 'rendered': 'day-progress-gnome-shell-extnsion' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': '',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1920,
        'height': 1008,
        'file': '2024\/05\/day-progress-gnome-shell-extnsion.jpg',
        'filesize': 211209,
        'sizes': {
          'medium': {
            'file': 'day-progress-gnome-shell-extnsion-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 10739,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-300x158.jpg',
          },
          'large': {
            'file': 'day-progress-gnome-shell-extnsion-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 54483,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-840x441.jpg',
          },
          'thumbnail': {
            'file': 'day-progress-gnome-shell-extnsion-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 15651,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-350x200.jpg',
          },
          'medium_large': {
            'file': 'day-progress-gnome-shell-extnsion-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 47433,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-768x403.jpg',
          },
          '1536x1536': {
            'file': 'day-progress-gnome-shell-extnsion-1536x806.jpg',
            'width': 1536,
            'height': 806,
            'filesize': 130044,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-1536x806.jpg',
          },
          'square-150': {
            'file': 'day-progress-gnome-shell-extnsion-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 6694,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-150x150.jpg',
          },
          'post-list': {
            'file': 'day-progress-gnome-shell-extnsion-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 19597,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-406x232.jpg',
          },
          'featured-post': {
            'file': 'day-progress-gnome-shell-extnsion-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 58448,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion-840x480.jpg',
          },
          'full': {
            'file': 'day-progress-gnome-shell-extnsion.jpg',
            'width': 1920,
            'height': 1008,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/day-progress-gnome-shell-extnsion.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283249' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=283249',
        }],
      },
    }],
  },
}, {
  'id': 283136,
  'date_gmt': '2024-05-26T17:21:11',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/cascadia-code-font-update-large-type-pieces',
  'title': { 'rendered': 'Microsoft Gives its Open-Source Developer Font Major Update' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283141',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 283141,
      'date': '2024-05-26T18:07:35',
      'slug': 'cascadia-code-update',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/cascadia-code-font-update-large-type-pieces\/cascadia-code-update',
      'title': { 'rendered': 'cascadia-code-update' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': '',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1920,
        'height': 1008,
        'file': '2024\/05\/cascadia-code-update.jpg',
        'filesize': 231136,
        'sizes': {
          'medium': {
            'file': 'cascadia-code-update-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 13110,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-300x158.jpg',
          },
          'large': {
            'file': 'cascadia-code-update-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 66437,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-840x441.jpg',
          },
          'thumbnail': {
            'file': 'cascadia-code-update-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 19148,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-350x200.jpg',
          },
          'medium_large': {
            'file': 'cascadia-code-update-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 59855,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-768x403.jpg',
          },
          '1536x1536': {
            'file': 'cascadia-code-update-1536x806.jpg',
            'width': 1536,
            'height': 806,
            'filesize': 150080,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-1536x806.jpg',
          },
          'square-150': {
            'file': 'cascadia-code-update-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 9241,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-150x150.jpg',
          },
          'post-list': {
            'file': 'cascadia-code-update-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 25360,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-406x232.jpg',
          },
          'featured-post': {
            'file': 'cascadia-code-update-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 72544,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update-840x480.jpg',
          },
          'full': {
            'file': 'cascadia-code-update.jpg',
            'width': 1920,
            'height': 1008,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/cascadia-code-update.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283141' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=283141',
        }],
      },
    }],
  },
}, {
  'id': 283080,
  'date_gmt': '2024-05-24T14:07:37',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/rufus-usb-ubuntu-24-04-persistence',
  'title': { 'rendered': 'Rufus Fixes Creation of Persistent Ubuntu 24.04 USBs' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/105571',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 105571,
      'date': '2016-03-31T20:29:38',
      'slug': 'usb-live-boot',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2016\/04\/how-to-create-a-bootable-ubuntu-usb-on-windows-mac-and-linux\/usb-live-boot',
      'title': { 'rendered': 'usb-live-boot' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '<p>It&#8217;s testing season<\/p>\n' },
      'alt_text': 'usb thumb drive ubuntu',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 800,
        'height': 449,
        'file': '2016\/04\/usb-live-boot.jpg',
        'sizes': {
          'medium': {
            'file': 'usb-live-boot-300x168.jpg',
            'width': 300,
            'height': 168,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-300x168.jpg',
          },
          'large': {
            'file': 'usb-live-boot-750x421.jpg',
            'width': 750,
            'height': 421,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-750x421.jpg',
          },
          'thumbnail': {
            'file': 'usb-live-boot-350x200.jpg',
            'width': 350,
            'height': 200,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-350x200.jpg',
          },
          'medium_large': {
            'file': 'usb-live-boot-768x431.jpg',
            'width': 768,
            'height': 431,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-768x431.jpg',
          },
          'square-150': {
            'file': 'usb-live-boot-150x150.jpg',
            'width': 150,
            'height': 150,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-150x150.jpg',
          },
          'post-list': {
            'file': 'usb-live-boot-406x232.jpg',
            'width': 406,
            'height': 232,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-406x232.jpg',
          },
          'thumbnail-sidebar': {
            'file': 'usb-live-boot-32x32.jpg',
            'width': 32,
            'height': 32,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-32x32.jpg',
          },
          'thumbnail-small': {
            'file': 'usb-live-boot-145x100.jpg',
            'width': 145,
            'height': 100,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-145x100.jpg',
          },
          'post-list_old_350x200': {
            'file': 'usb-live-boot-350x200.jpg',
            'width': 350,
            'height': 200,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot-350x200.jpg',
          },
          'full': {
            'file': 'usb-live-boot.jpg',
            'width': 800,
            'height': 449,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2016\/04\/usb-live-boot.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/105571' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=105571',
        }],
      },
    }],
  },
}, {
  'id': 283052,
  'date_gmt': '2024-05-23T15:02:35',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/snap-store-website-new-look',
  'title': { 'rendered': 'Snap Store Website Redesign Goes Live \u2013 And It Looks Good' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/266060',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 266060,
      'date': '2023-05-30T22:34:20',
      'slug': 'ubuntu-logo-and-the-snapcraft-logo-tiled',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2023\/05\/immutable-all-snap-ubuntu-desktop\/ubuntu-logo-and-the-snapcraft-logo-tiled',
      'title': { 'rendered': 'ubuntu logo and the snapcraft logo tiled' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': 'ubuntu logo and the snapcraft logo tiled',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1920,
        'height': 1032,
        'file': '2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled.jpg',
        'filesize': 119219,
        'sizes': {
          'medium': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-300x161.jpg',
            'width': 300,
            'height': 161,
            'filesize': 14551,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-300x161.jpg',
          },
          'large': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-840x452.jpg',
            'width': 840,
            'height': 452,
            'filesize': 48619,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-840x452.jpg',
          },
          'thumbnail': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 17432,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-350x200.jpg',
          },
          'medium_large': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-768x413.jpg',
            'width': 768,
            'height': 413,
            'filesize': 43356,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-768x413.jpg',
          },
          '1536x1536': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-1536x826.jpg',
            'width': 1536,
            'height': 826,
            'filesize': 100648,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-1536x826.jpg',
          },
          'square-150': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 7686,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-150x150.jpg',
          },
          'post-list': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 20838,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-406x232.jpg',
          },
          'featured-post': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 48759,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled-840x480.jpg',
          },
          'full': {
            'file': 'ubuntu-logo-and-the-snapcraft-logo-tiled.jpg',
            'width': 1920,
            'height': 1032,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2023\/05\/ubuntu-logo-and-the-snapcraft-logo-tiled.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/266060' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=266060',
        }],
      },
    }],
  },
}, {
  'id': 282972,
  'date_gmt': '2024-05-22T16:51:26',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/ubuntu-24-04-upgrades-officially-open',
  'title': { 'rendered': 'Ubuntu 24.04 LTS Upgrades Now Officially Enabled' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283036',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 283036,
      'date': '2024-05-23T00:56:25',
      'slug': 'noble-upgrade-tile',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/ubuntu-24-04-upgrades-officially-open\/noble-upgrade-tile',
      'title': { 'rendered': 'noble-upgrade-tile' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': '',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 1371,
        'height': 720,
        'file': '2024\/05\/noble-upgrade-tile.jpg',
        'filesize': 190687,
        'sizes': {
          'medium': {
            'file': 'noble-upgrade-tile-300x158.jpg',
            'width': 300,
            'height': 158,
            'filesize': 12912,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile-300x158.jpg',
          },
          'large': {
            'file': 'noble-upgrade-tile-840x441.jpg',
            'width': 840,
            'height': 441,
            'filesize': 64366,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile-840x441.jpg',
          },
          'thumbnail': {
            'file': 'noble-upgrade-tile-350x200.jpg',
            'width': 350,
            'height': 200,
            'filesize': 17240,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile-350x200.jpg',
          },
          'medium_large': {
            'file': 'noble-upgrade-tile-768x403.jpg',
            'width': 768,
            'height': 403,
            'filesize': 55982,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile-768x403.jpg',
          },
          'square-150': {
            'file': 'noble-upgrade-tile-150x150.jpg',
            'width': 150,
            'height': 150,
            'filesize': 7057,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile-150x150.jpg',
          },
          'post-list': {
            'file': 'noble-upgrade-tile-406x232.jpg',
            'width': 406,
            'height': 232,
            'filesize': 21555,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile-406x232.jpg',
          },
          'featured-post': {
            'file': 'noble-upgrade-tile-840x480.jpg',
            'width': 840,
            'height': 480,
            'filesize': 65920,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile-840x480.jpg',
          },
          'full': {
            'file': 'noble-upgrade-tile.jpg',
            'width': 1371,
            'height': 720,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2024\/05\/noble-upgrade-tile.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/283036' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=283036',
        }],
      },
    }],
  },
}, {
  'id': 282962,
  'date_gmt': '2024-05-22T15:45:05',
  'link': 'https:\/\/www.omgubuntu.co.uk\/2024\/05\/mozilla-shares-firefox-roadmap',
  'title': { 'rendered': 'Mozilla Reveals New Features Coming to Firefox' },
  '_links': {
    'wp:featuredmedia': [{
      'embeddable': true,
      'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/156210',
    }],
  },
  '_embedded': {
    'wp:featuredmedia': [{
      'id': 156210,
      'date': '2019-11-14T00:50:05',
      'slug': 'firefox-6',
      'type': 'attachment',
      'link': 'https:\/\/www.omgubuntu.co.uk\/2019\/12\/firefox-71-released-download\/firefox-6',
      'title': { 'rendered': 'Mozilla Firefox Browser Logo' },
      'author': 3,
      'featured_media': 0,
      'jetpack_sharing_enabled': true,
      'amp_enabled': true,
      'acf': [],
      'caption': { 'rendered': '' },
      'alt_text': 'Mozilla Firefox Logo',
      'media_type': 'image',
      'mime_type': 'image\/jpeg',
      'media_details': {
        'width': 840,
        'height': 480,
        'file': '2019\/11\/firefox-1.jpg',
        'sizes': {
          'medium': {
            'file': 'firefox-1-300x171.jpg',
            'width': 300,
            'height': 171,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-300x171.jpg',
          },
          'large': {
            'file': 'firefox-1-750x429.jpg',
            'width': 750,
            'height': 429,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-750x429.jpg',
          },
          'thumbnail': {
            'file': 'firefox-1-350x200.jpg',
            'width': 350,
            'height': 200,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-350x200.jpg',
          },
          'medium_large': {
            'file': 'firefox-1-768x439.jpg',
            'width': 768,
            'height': 439,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-768x439.jpg',
          },
          'square-150': {
            'file': 'firefox-1-150x150.jpg',
            'width': 150,
            'height': 150,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-150x150.jpg',
          },
          'post-list': {
            'file': 'firefox-1-406x232.jpg',
            'width': 406,
            'height': 232,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-406x232.jpg',
          },
          'thumbnail-sidebar': {
            'file': 'firefox-1-145x100.jpg',
            'width': 145,
            'height': 100,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-145x100.jpg',
          },
          'thumbnail-small': {
            'file': 'firefox-1-145x100.jpg',
            'width': 145,
            'height': 100,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1-145x100.jpg',
          },
          'full': {
            'file': 'firefox-1.jpg',
            'width': 840,
            'height': 480,
            'mime_type': 'image\/jpeg',
            'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1.jpg',
          },
        },
        'image_meta': {
          'aperture': '0',
          'credit': '',
          'camera': '',
          'caption': '',
          'created_timestamp': '0',
          'copyright': '',
          'focal_length': '0',
          'iso': '0',
          'shutter_speed': '0',
          'title': '',
          'orientation': '0',
          'keywords': [],
        },
      },
      'source_url': 'https:\/\/www.omgubuntu.co.uk\/wp-content\/uploads\/2019\/11\/firefox-1.jpg',
      '_links': {
        'self': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media\/156210' }],
        'collection': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/media' }],
        'about': [{ 'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/types\/attachment' }],
        'author': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/users\/3',
        }],
        'replies': [{
          'embeddable': true,
          'href': 'https:\/\/www.omgubuntu.co.uk\/wp-json\/wp\/v2\/comments?post=156210',
        }],
      },
    }],
  },
}];
